// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.21.0
// 	protoc        v3.9.2
// source: order.proto

package order

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type BusinessServiceOrder struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BusinessServiceOrderID  int64  `protobuf:"varint,1,opt,name=businessServiceOrderID,proto3" json:"businessServiceOrderID,omitempty"`
	ClientID                int64  `protobuf:"varint,2,opt,name=clientID,proto3" json:"clientID,omitempty"`
	BusinessServiceID       int64  `protobuf:"varint,3,opt,name=businessServiceID,proto3" json:"businessServiceID,omitempty"`
	StartAt                 string `protobuf:"bytes,4,opt,name=startAt,proto3" json:"startAt,omitempty"`
	EndAt                   string `protobuf:"bytes,5,opt,name=endAt,proto3" json:"endAt,omitempty"`
	CreatedAt               string `protobuf:"bytes,6,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	PrePaid                 bool   `protobuf:"varint,7,opt,name=prePaid,proto3" json:"prePaid,omitempty"`
	ClientFirstName         string `protobuf:"bytes,8,opt,name=clientFirstName,proto3" json:"clientFirstName,omitempty"`
	ClientPhoneNumber       string `protobuf:"bytes,9,opt,name=clientPhoneNumber,proto3" json:"clientPhoneNumber,omitempty"`
	ClientPhoneNumberPrefix string `protobuf:"bytes,10,opt,name=clientPhoneNumberPrefix,proto3" json:"clientPhoneNumberPrefix,omitempty"`
	ClientCommentary        string `protobuf:"bytes,11,opt,name=clientCommentary,proto3" json:"clientCommentary,omitempty"`
}

func (x *BusinessServiceOrder) Reset() {
	*x = BusinessServiceOrder{}
	if protoimpl.UnsafeEnabled {
		mi := &file_order_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BusinessServiceOrder) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BusinessServiceOrder) ProtoMessage() {}

func (x *BusinessServiceOrder) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BusinessServiceOrder.ProtoReflect.Descriptor instead.
func (*BusinessServiceOrder) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{0}
}

func (x *BusinessServiceOrder) GetBusinessServiceOrderID() int64 {
	if x != nil {
		return x.BusinessServiceOrderID
	}
	return 0
}

func (x *BusinessServiceOrder) GetClientID() int64 {
	if x != nil {
		return x.ClientID
	}
	return 0
}

func (x *BusinessServiceOrder) GetBusinessServiceID() int64 {
	if x != nil {
		return x.BusinessServiceID
	}
	return 0
}

func (x *BusinessServiceOrder) GetStartAt() string {
	if x != nil {
		return x.StartAt
	}
	return ""
}

func (x *BusinessServiceOrder) GetEndAt() string {
	if x != nil {
		return x.EndAt
	}
	return ""
}

func (x *BusinessServiceOrder) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *BusinessServiceOrder) GetPrePaid() bool {
	if x != nil {
		return x.PrePaid
	}
	return false
}

func (x *BusinessServiceOrder) GetClientFirstName() string {
	if x != nil {
		return x.ClientFirstName
	}
	return ""
}

func (x *BusinessServiceOrder) GetClientPhoneNumber() string {
	if x != nil {
		return x.ClientPhoneNumber
	}
	return ""
}

func (x *BusinessServiceOrder) GetClientPhoneNumberPrefix() string {
	if x != nil {
		return x.ClientPhoneNumberPrefix
	}
	return ""
}

func (x *BusinessServiceOrder) GetClientCommentary() string {
	if x != nil {
		return x.ClientCommentary
	}
	return ""
}

type GetBusinessServiceOrderRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BusinessServiceOrderID int64 `protobuf:"varint,1,opt,name=businessServiceOrderID,proto3" json:"businessServiceOrderID,omitempty"`
}

func (x *GetBusinessServiceOrderRequest) Reset() {
	*x = GetBusinessServiceOrderRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_order_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetBusinessServiceOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBusinessServiceOrderRequest) ProtoMessage() {}

func (x *GetBusinessServiceOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBusinessServiceOrderRequest.ProtoReflect.Descriptor instead.
func (*GetBusinessServiceOrderRequest) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{1}
}

func (x *GetBusinessServiceOrderRequest) GetBusinessServiceOrderID() int64 {
	if x != nil {
		return x.BusinessServiceOrderID
	}
	return 0
}

type GetBusinessServiceOrderResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BusinessServiceOrder *BusinessServiceOrder `protobuf:"bytes,1,opt,name=businessServiceOrder,proto3" json:"businessServiceOrder,omitempty"`
}

func (x *GetBusinessServiceOrderResponse) Reset() {
	*x = GetBusinessServiceOrderResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_order_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetBusinessServiceOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBusinessServiceOrderResponse) ProtoMessage() {}

func (x *GetBusinessServiceOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBusinessServiceOrderResponse.ProtoReflect.Descriptor instead.
func (*GetBusinessServiceOrderResponse) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{2}
}

func (x *GetBusinessServiceOrderResponse) GetBusinessServiceOrder() *BusinessServiceOrder {
	if x != nil {
		return x.BusinessServiceOrder
	}
	return nil
}

type GetBusinessServiceOrdersRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BusinessServiceID int64 `protobuf:"varint,1,opt,name=businessServiceID,proto3" json:"businessServiceID,omitempty"`
}

func (x *GetBusinessServiceOrdersRequest) Reset() {
	*x = GetBusinessServiceOrdersRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_order_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetBusinessServiceOrdersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBusinessServiceOrdersRequest) ProtoMessage() {}

func (x *GetBusinessServiceOrdersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBusinessServiceOrdersRequest.ProtoReflect.Descriptor instead.
func (*GetBusinessServiceOrdersRequest) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{3}
}

func (x *GetBusinessServiceOrdersRequest) GetBusinessServiceID() int64 {
	if x != nil {
		return x.BusinessServiceID
	}
	return 0
}

type GetBusinessServiceOrdersResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BusinessServicesOrders []*BusinessServiceOrder `protobuf:"bytes,1,rep,name=businessServicesOrders,proto3" json:"businessServicesOrders,omitempty"`
}

func (x *GetBusinessServiceOrdersResponse) Reset() {
	*x = GetBusinessServiceOrdersResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_order_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetBusinessServiceOrdersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBusinessServiceOrdersResponse) ProtoMessage() {}

func (x *GetBusinessServiceOrdersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBusinessServiceOrdersResponse.ProtoReflect.Descriptor instead.
func (*GetBusinessServiceOrdersResponse) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{4}
}

func (x *GetBusinessServiceOrdersResponse) GetBusinessServicesOrders() []*BusinessServiceOrder {
	if x != nil {
		return x.BusinessServicesOrders
	}
	return nil
}

type CreateBusinessServiceOrderRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ClientID                int64  `protobuf:"varint,1,opt,name=clientID,proto3" json:"clientID,omitempty"`
	BusinessServiceID       int64  `protobuf:"varint,2,opt,name=businessServiceID,proto3" json:"businessServiceID,omitempty"`
	StartAt                 string `protobuf:"bytes,3,opt,name=startAt,proto3" json:"startAt,omitempty"`
	PrePaid                 bool   `protobuf:"varint,4,opt,name=prePaid,proto3" json:"prePaid,omitempty"`
	ClientFirstName         string `protobuf:"bytes,5,opt,name=clientFirstName,proto3" json:"clientFirstName,omitempty"`
	ClientPhoneNumber       string `protobuf:"bytes,6,opt,name=clientPhoneNumber,proto3" json:"clientPhoneNumber,omitempty"`
	ClientPhoneNumberPrefix string `protobuf:"bytes,7,opt,name=clientPhoneNumberPrefix,proto3" json:"clientPhoneNumberPrefix,omitempty"`
	ClientCommentary        string `protobuf:"bytes,8,opt,name=clientCommentary,proto3" json:"clientCommentary,omitempty"`
}

func (x *CreateBusinessServiceOrderRequest) Reset() {
	*x = CreateBusinessServiceOrderRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_order_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateBusinessServiceOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBusinessServiceOrderRequest) ProtoMessage() {}

func (x *CreateBusinessServiceOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBusinessServiceOrderRequest.ProtoReflect.Descriptor instead.
func (*CreateBusinessServiceOrderRequest) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{5}
}

func (x *CreateBusinessServiceOrderRequest) GetClientID() int64 {
	if x != nil {
		return x.ClientID
	}
	return 0
}

func (x *CreateBusinessServiceOrderRequest) GetBusinessServiceID() int64 {
	if x != nil {
		return x.BusinessServiceID
	}
	return 0
}

func (x *CreateBusinessServiceOrderRequest) GetStartAt() string {
	if x != nil {
		return x.StartAt
	}
	return ""
}

func (x *CreateBusinessServiceOrderRequest) GetPrePaid() bool {
	if x != nil {
		return x.PrePaid
	}
	return false
}

func (x *CreateBusinessServiceOrderRequest) GetClientFirstName() string {
	if x != nil {
		return x.ClientFirstName
	}
	return ""
}

func (x *CreateBusinessServiceOrderRequest) GetClientPhoneNumber() string {
	if x != nil {
		return x.ClientPhoneNumber
	}
	return ""
}

func (x *CreateBusinessServiceOrderRequest) GetClientPhoneNumberPrefix() string {
	if x != nil {
		return x.ClientPhoneNumberPrefix
	}
	return ""
}

func (x *CreateBusinessServiceOrderRequest) GetClientCommentary() string {
	if x != nil {
		return x.ClientCommentary
	}
	return ""
}

type CreateBusinessServiceOrderResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BusinessServiceOrder *BusinessServiceOrder `protobuf:"bytes,1,opt,name=businessServiceOrder,proto3" json:"businessServiceOrder,omitempty"`
}

func (x *CreateBusinessServiceOrderResponse) Reset() {
	*x = CreateBusinessServiceOrderResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_order_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateBusinessServiceOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBusinessServiceOrderResponse) ProtoMessage() {}

func (x *CreateBusinessServiceOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBusinessServiceOrderResponse.ProtoReflect.Descriptor instead.
func (*CreateBusinessServiceOrderResponse) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{6}
}

func (x *CreateBusinessServiceOrderResponse) GetBusinessServiceOrder() *BusinessServiceOrder {
	if x != nil {
		return x.BusinessServiceOrder
	}
	return nil
}

var File_order_proto protoreflect.FileDescriptor

var file_order_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x14, 0x62,
	0x75, 0x73, 0x69, 0x6e, 0x65, 0x73, 0x73, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x4f, 0x72,
	0x64, 0x65, 0x72, 0x22, 0xbe, 0x03, 0x0a, 0x14, 0x42, 0x75, 0x73, 0x69, 0x6e, 0x65, 0x73, 0x73,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x12, 0x36, 0x0a, 0x16,
	0x62, 0x75, 0x73, 0x69, 0x6e, 0x65, 0x73, 0x73, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x4f,
	0x72, 0x64, 0x65, 0x72, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x16, 0x62, 0x75,
	0x73, 0x69, 0x6e, 0x65, 0x73, 0x73, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x4f, 0x72, 0x64,
	0x65, 0x72, 0x49, 0x44, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x49, 0x44,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x49, 0x44,
	0x12, 0x2c, 0x0a, 0x11, 0x62, 0x75, 0x73, 0x69, 0x6e, 0x65, 0x73, 0x73, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x49, 0x44, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x11, 0x62, 0x75, 0x73,
	0x69, 0x6e, 0x65, 0x73, 0x73, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x49, 0x44, 0x12, 0x18,
	0x0a, 0x07, 0x73, 0x74, 0x61, 0x72, 0x74, 0x41, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x73, 0x74, 0x61, 0x72, 0x74, 0x41, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x6e, 0x64, 0x41,
	0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x6e, 0x64, 0x41, 0x74, 0x12, 0x1c,
	0x0a, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x18, 0x0a, 0x07,
	0x70, 0x72, 0x65, 0x50, 0x61, 0x69, 0x64, 0x18, 0x07, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x70,
	0x72, 0x65, 0x50, 0x61, 0x69, 0x64, 0x12, 0x28, 0x0a, 0x0f, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74,
	0x46, 0x69, 0x72, 0x73, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0f, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x46, 0x69, 0x72, 0x73, 0x74, 0x4e, 0x61, 0x6d, 0x65,
	0x12, 0x2c, 0x0a, 0x11, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x50, 0x68, 0x6f, 0x6e, 0x65, 0x4e,
	0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x11, 0x63, 0x6c, 0x69,
	0x65, 0x6e, 0x74, 0x50, 0x68, 0x6f, 0x6e, 0x65, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x38,
	0x0a, 0x17, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x50, 0x68, 0x6f, 0x6e, 0x65, 0x4e, 0x75, 0x6d,
	0x62, 0x65, 0x72, 0x50, 0x72, 0x65, 0x66, 0x69, 0x78, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x17, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x50, 0x68, 0x6f, 0x6e, 0x65, 0x4e, 0x75, 0x6d, 0x62,
	0x65, 0x72, 0x50, 0x72, 0x65, 0x66, 0x69, 0x78, 0x12, 0x2a, 0x0a, 0x10, 0x63, 0x6c, 0x69, 0x65,
	0x6e, 0x74, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x61, 0x72, 0x79, 0x18, 0x0b, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x10, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e,
	0x74, 0x61, 0x72, 0x79, 0x22, 0x58, 0x0a, 0x1e, 0x47, 0x65, 0x74, 0x42, 0x75, 0x73, 0x69, 0x6e,
	0x65, 0x73, 0x73, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x36, 0x0a, 0x16, 0x62, 0x75, 0x73, 0x69, 0x6e, 0x65,
	0x73, 0x73, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x49, 0x44,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x16, 0x62, 0x75, 0x73, 0x69, 0x6e, 0x65, 0x73, 0x73,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x49, 0x44, 0x22, 0x81,
	0x01, 0x0a, 0x1f, 0x47, 0x65, 0x74, 0x42, 0x75, 0x73, 0x69, 0x6e, 0x65, 0x73, 0x73, 0x53, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x5e, 0x0a, 0x14, 0x62, 0x75, 0x73, 0x69, 0x6e, 0x65, 0x73, 0x73, 0x53, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x2a, 0x2e, 0x62, 0x75, 0x73, 0x69, 0x6e, 0x65, 0x73, 0x73, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x2e, 0x42, 0x75, 0x73, 0x69, 0x6e, 0x65, 0x73, 0x73,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x14, 0x62, 0x75,
	0x73, 0x69, 0x6e, 0x65, 0x73, 0x73, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x4f, 0x72, 0x64,
	0x65, 0x72, 0x22, 0x4f, 0x0a, 0x1f, 0x47, 0x65, 0x74, 0x42, 0x75, 0x73, 0x69, 0x6e, 0x65, 0x73,
	0x73, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x73, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2c, 0x0a, 0x11, 0x62, 0x75, 0x73, 0x69, 0x6e, 0x65, 0x73,
	0x73, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x11, 0x62, 0x75, 0x73, 0x69, 0x6e, 0x65, 0x73, 0x73, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x49, 0x44, 0x22, 0x86, 0x01, 0x0a, 0x20, 0x47, 0x65, 0x74, 0x42, 0x75, 0x73, 0x69, 0x6e,
	0x65, 0x73, 0x73, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x73,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x62, 0x0a, 0x16, 0x62, 0x75, 0x73, 0x69,
	0x6e, 0x65, 0x73, 0x73, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x4f, 0x72, 0x64, 0x65,
	0x72, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x2a, 0x2e, 0x62, 0x75, 0x73, 0x69, 0x6e,
	0x65, 0x73, 0x73, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x2e,
	0x42, 0x75, 0x73, 0x69, 0x6e, 0x65, 0x73, 0x73, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x4f,
	0x72, 0x64, 0x65, 0x72, 0x52, 0x16, 0x62, 0x75, 0x73, 0x69, 0x6e, 0x65, 0x73, 0x73, 0x53, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x73, 0x22, 0xdf, 0x02, 0x0a,
	0x21, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x42, 0x75, 0x73, 0x69, 0x6e, 0x65, 0x73, 0x73, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x49, 0x44, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x49, 0x44, 0x12, 0x2c,
	0x0a, 0x11, 0x62, 0x75, 0x73, 0x69, 0x6e, 0x65, 0x73, 0x73, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x11, 0x62, 0x75, 0x73, 0x69, 0x6e,
	0x65, 0x73, 0x73, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x49, 0x44, 0x12, 0x18, 0x0a, 0x07,
	0x73, 0x74, 0x61, 0x72, 0x74, 0x41, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x73,
	0x74, 0x61, 0x72, 0x74, 0x41, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x72, 0x65, 0x50, 0x61, 0x69,
	0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x70, 0x72, 0x65, 0x50, 0x61, 0x69, 0x64,
	0x12, 0x28, 0x0a, 0x0f, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x46, 0x69, 0x72, 0x73, 0x74, 0x4e,
	0x61, 0x6d, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x63, 0x6c, 0x69, 0x65, 0x6e,
	0x74, 0x46, 0x69, 0x72, 0x73, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x2c, 0x0a, 0x11, 0x63, 0x6c,
	0x69, 0x65, 0x6e, 0x74, 0x50, 0x68, 0x6f, 0x6e, 0x65, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18,
	0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x11, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x50, 0x68, 0x6f,
	0x6e, 0x65, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x38, 0x0a, 0x17, 0x63, 0x6c, 0x69, 0x65,
	0x6e, 0x74, 0x50, 0x68, 0x6f, 0x6e, 0x65, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x50, 0x72, 0x65,
	0x66, 0x69, 0x78, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x17, 0x63, 0x6c, 0x69, 0x65, 0x6e,
	0x74, 0x50, 0x68, 0x6f, 0x6e, 0x65, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x50, 0x72, 0x65, 0x66,
	0x69, 0x78, 0x12, 0x2a, 0x0a, 0x10, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x43, 0x6f, 0x6d, 0x6d,
	0x65, 0x6e, 0x74, 0x61, 0x72, 0x79, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x10, 0x63, 0x6c,
	0x69, 0x65, 0x6e, 0x74, 0x43, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x74, 0x61, 0x72, 0x79, 0x22, 0x84,
	0x01, 0x0a, 0x22, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x42, 0x75, 0x73, 0x69, 0x6e, 0x65, 0x73,
	0x73, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x5e, 0x0a, 0x14, 0x62, 0x75, 0x73, 0x69, 0x6e, 0x65, 0x73,
	0x73, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x2a, 0x2e, 0x62, 0x75, 0x73, 0x69, 0x6e, 0x65, 0x73, 0x73, 0x53, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x2e, 0x42, 0x75, 0x73, 0x69, 0x6e,
	0x65, 0x73, 0x73, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x52,
	0x14, 0x62, 0x75, 0x73, 0x69, 0x6e, 0x65, 0x73, 0x73, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x4f, 0x72, 0x64, 0x65, 0x72, 0x32, 0xc4, 0x03, 0x0a, 0x15, 0x42, 0x75, 0x73, 0x69, 0x6e, 0x65,
	0x73, 0x73, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x73, 0x12,
	0x88, 0x01, 0x0a, 0x17, 0x47, 0x65, 0x74, 0x42, 0x75, 0x73, 0x69, 0x6e, 0x65, 0x73, 0x73, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x12, 0x34, 0x2e, 0x62, 0x75,
	0x73, 0x69, 0x6e, 0x65, 0x73, 0x73, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x4f, 0x72, 0x64,
	0x65, 0x72, 0x2e, 0x47, 0x65, 0x74, 0x42, 0x75, 0x73, 0x69, 0x6e, 0x65, 0x73, 0x73, 0x53, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x35, 0x2e, 0x62, 0x75, 0x73, 0x69, 0x6e, 0x65, 0x73, 0x73, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x2e, 0x47, 0x65, 0x74, 0x42, 0x75, 0x73, 0x69,
	0x6e, 0x65, 0x73, 0x73, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x4f, 0x72, 0x64, 0x65, 0x72,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x8b, 0x01, 0x0a, 0x18, 0x47,
	0x65, 0x74, 0x42, 0x75, 0x73, 0x69, 0x6e, 0x65, 0x73, 0x73, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x73, 0x12, 0x35, 0x2e, 0x62, 0x75, 0x73, 0x69, 0x6e, 0x65,
	0x73, 0x73, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x2e, 0x47,
	0x65, 0x74, 0x42, 0x75, 0x73, 0x69, 0x6e, 0x65, 0x73, 0x73, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x36,
	0x2e, 0x62, 0x75, 0x73, 0x69, 0x6e, 0x65, 0x73, 0x73, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x4f, 0x72, 0x64, 0x65, 0x72, 0x2e, 0x47, 0x65, 0x74, 0x42, 0x75, 0x73, 0x69, 0x6e, 0x65, 0x73,
	0x73, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x73, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x91, 0x01, 0x0a, 0x1a, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x42, 0x75, 0x73, 0x69, 0x6e, 0x65, 0x73, 0x73, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x12, 0x37, 0x2e, 0x62, 0x75, 0x73, 0x69, 0x6e, 0x65,
	0x73, 0x73, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x2e, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x42, 0x75, 0x73, 0x69, 0x6e, 0x65, 0x73, 0x73, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x38, 0x2e, 0x62, 0x75, 0x73, 0x69, 0x6e, 0x65, 0x73, 0x73, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x42, 0x75,
	0x73, 0x69, 0x6e, 0x65, 0x73, 0x73, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x4f, 0x72, 0x64,
	0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x09, 0x5a, 0x07,
	0x2e, 0x3b, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_order_proto_rawDescOnce sync.Once
	file_order_proto_rawDescData = file_order_proto_rawDesc
)

func file_order_proto_rawDescGZIP() []byte {
	file_order_proto_rawDescOnce.Do(func() {
		file_order_proto_rawDescData = protoimpl.X.CompressGZIP(file_order_proto_rawDescData)
	})
	return file_order_proto_rawDescData
}

var file_order_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_order_proto_goTypes = []interface{}{
	(*BusinessServiceOrder)(nil),               // 0: businessServiceOrder.BusinessServiceOrder
	(*GetBusinessServiceOrderRequest)(nil),     // 1: businessServiceOrder.GetBusinessServiceOrderRequest
	(*GetBusinessServiceOrderResponse)(nil),    // 2: businessServiceOrder.GetBusinessServiceOrderResponse
	(*GetBusinessServiceOrdersRequest)(nil),    // 3: businessServiceOrder.GetBusinessServiceOrdersRequest
	(*GetBusinessServiceOrdersResponse)(nil),   // 4: businessServiceOrder.GetBusinessServiceOrdersResponse
	(*CreateBusinessServiceOrderRequest)(nil),  // 5: businessServiceOrder.CreateBusinessServiceOrderRequest
	(*CreateBusinessServiceOrderResponse)(nil), // 6: businessServiceOrder.CreateBusinessServiceOrderResponse
}
var file_order_proto_depIdxs = []int32{
	0, // 0: businessServiceOrder.GetBusinessServiceOrderResponse.businessServiceOrder:type_name -> businessServiceOrder.BusinessServiceOrder
	0, // 1: businessServiceOrder.GetBusinessServiceOrdersResponse.businessServicesOrders:type_name -> businessServiceOrder.BusinessServiceOrder
	0, // 2: businessServiceOrder.CreateBusinessServiceOrderResponse.businessServiceOrder:type_name -> businessServiceOrder.BusinessServiceOrder
	1, // 3: businessServiceOrder.BusinessServiceOrders.GetBusinessServiceOrder:input_type -> businessServiceOrder.GetBusinessServiceOrderRequest
	3, // 4: businessServiceOrder.BusinessServiceOrders.GetBusinessServiceOrders:input_type -> businessServiceOrder.GetBusinessServiceOrdersRequest
	5, // 5: businessServiceOrder.BusinessServiceOrders.CreateBusinessServiceOrder:input_type -> businessServiceOrder.CreateBusinessServiceOrderRequest
	2, // 6: businessServiceOrder.BusinessServiceOrders.GetBusinessServiceOrder:output_type -> businessServiceOrder.GetBusinessServiceOrderResponse
	4, // 7: businessServiceOrder.BusinessServiceOrders.GetBusinessServiceOrders:output_type -> businessServiceOrder.GetBusinessServiceOrdersResponse
	6, // 8: businessServiceOrder.BusinessServiceOrders.CreateBusinessServiceOrder:output_type -> businessServiceOrder.CreateBusinessServiceOrderResponse
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_order_proto_init() }
func file_order_proto_init() {
	if File_order_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_order_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BusinessServiceOrder); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_order_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetBusinessServiceOrderRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_order_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetBusinessServiceOrderResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_order_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetBusinessServiceOrdersRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_order_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetBusinessServiceOrdersResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_order_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateBusinessServiceOrderRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_order_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateBusinessServiceOrderResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_order_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_order_proto_goTypes,
		DependencyIndexes: file_order_proto_depIdxs,
		MessageInfos:      file_order_proto_msgTypes,
	}.Build()
	File_order_proto = out.File
	file_order_proto_rawDesc = nil
	file_order_proto_goTypes = nil
	file_order_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// BusinessServiceOrdersClient is the client API for BusinessServiceOrders service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type BusinessServiceOrdersClient interface {
	GetBusinessServiceOrder(ctx context.Context, in *GetBusinessServiceOrderRequest, opts ...grpc.CallOption) (*GetBusinessServiceOrderResponse, error)
	GetBusinessServiceOrders(ctx context.Context, in *GetBusinessServiceOrdersRequest, opts ...grpc.CallOption) (*GetBusinessServiceOrdersResponse, error)
	CreateBusinessServiceOrder(ctx context.Context, in *CreateBusinessServiceOrderRequest, opts ...grpc.CallOption) (*CreateBusinessServiceOrderResponse, error)
}

type businessServiceOrdersClient struct {
	cc grpc.ClientConnInterface
}

func NewBusinessServiceOrdersClient(cc grpc.ClientConnInterface) BusinessServiceOrdersClient {
	return &businessServiceOrdersClient{cc}
}

func (c *businessServiceOrdersClient) GetBusinessServiceOrder(ctx context.Context, in *GetBusinessServiceOrderRequest, opts ...grpc.CallOption) (*GetBusinessServiceOrderResponse, error) {
	out := new(GetBusinessServiceOrderResponse)
	err := c.cc.Invoke(ctx, "/businessServiceOrder.BusinessServiceOrders/GetBusinessServiceOrder", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *businessServiceOrdersClient) GetBusinessServiceOrders(ctx context.Context, in *GetBusinessServiceOrdersRequest, opts ...grpc.CallOption) (*GetBusinessServiceOrdersResponse, error) {
	out := new(GetBusinessServiceOrdersResponse)
	err := c.cc.Invoke(ctx, "/businessServiceOrder.BusinessServiceOrders/GetBusinessServiceOrders", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *businessServiceOrdersClient) CreateBusinessServiceOrder(ctx context.Context, in *CreateBusinessServiceOrderRequest, opts ...grpc.CallOption) (*CreateBusinessServiceOrderResponse, error) {
	out := new(CreateBusinessServiceOrderResponse)
	err := c.cc.Invoke(ctx, "/businessServiceOrder.BusinessServiceOrders/CreateBusinessServiceOrder", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BusinessServiceOrdersServer is the server API for BusinessServiceOrders service.
type BusinessServiceOrdersServer interface {
	GetBusinessServiceOrder(context.Context, *GetBusinessServiceOrderRequest) (*GetBusinessServiceOrderResponse, error)
	GetBusinessServiceOrders(context.Context, *GetBusinessServiceOrdersRequest) (*GetBusinessServiceOrdersResponse, error)
	CreateBusinessServiceOrder(context.Context, *CreateBusinessServiceOrderRequest) (*CreateBusinessServiceOrderResponse, error)
}

// UnimplementedBusinessServiceOrdersServer can be embedded to have forward compatible implementations.
type UnimplementedBusinessServiceOrdersServer struct {
}

func (*UnimplementedBusinessServiceOrdersServer) GetBusinessServiceOrder(context.Context, *GetBusinessServiceOrderRequest) (*GetBusinessServiceOrderResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBusinessServiceOrder not implemented")
}
func (*UnimplementedBusinessServiceOrdersServer) GetBusinessServiceOrders(context.Context, *GetBusinessServiceOrdersRequest) (*GetBusinessServiceOrdersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBusinessServiceOrders not implemented")
}
func (*UnimplementedBusinessServiceOrdersServer) CreateBusinessServiceOrder(context.Context, *CreateBusinessServiceOrderRequest) (*CreateBusinessServiceOrderResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateBusinessServiceOrder not implemented")
}

func RegisterBusinessServiceOrdersServer(s *grpc.Server, srv BusinessServiceOrdersServer) {
	s.RegisterService(&_BusinessServiceOrders_serviceDesc, srv)
}

func _BusinessServiceOrders_GetBusinessServiceOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBusinessServiceOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BusinessServiceOrdersServer).GetBusinessServiceOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/businessServiceOrder.BusinessServiceOrders/GetBusinessServiceOrder",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BusinessServiceOrdersServer).GetBusinessServiceOrder(ctx, req.(*GetBusinessServiceOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BusinessServiceOrders_GetBusinessServiceOrders_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBusinessServiceOrdersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BusinessServiceOrdersServer).GetBusinessServiceOrders(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/businessServiceOrder.BusinessServiceOrders/GetBusinessServiceOrders",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BusinessServiceOrdersServer).GetBusinessServiceOrders(ctx, req.(*GetBusinessServiceOrdersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BusinessServiceOrders_CreateBusinessServiceOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateBusinessServiceOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BusinessServiceOrdersServer).CreateBusinessServiceOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/businessServiceOrder.BusinessServiceOrders/CreateBusinessServiceOrder",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BusinessServiceOrdersServer).CreateBusinessServiceOrder(ctx, req.(*CreateBusinessServiceOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _BusinessServiceOrders_serviceDesc = grpc.ServiceDesc{
	ServiceName: "businessServiceOrder.BusinessServiceOrders",
	HandlerType: (*BusinessServiceOrdersServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetBusinessServiceOrder",
			Handler:    _BusinessServiceOrders_GetBusinessServiceOrder_Handler,
		},
		{
			MethodName: "GetBusinessServiceOrders",
			Handler:    _BusinessServiceOrders_GetBusinessServiceOrders_Handler,
		},
		{
			MethodName: "CreateBusinessServiceOrder",
			Handler:    _BusinessServiceOrders_CreateBusinessServiceOrder_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "order.proto",
}
